# ndarray的创建

In [1]:
import numpy as np

In [2]:
# 使用np.array创建基本的ndarray
# 里面元素默认类型为np.float64
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
# 创建多维ndarray
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# 查看ndarray对象的三个属性
arr2.ndim

2

In [5]:
arr2.shape

(2, 4)

In [6]:
arr2.dtype

dtype('int32')

In [7]:
arr1.dtype

dtype('float64')

In [8]:
# 其他创建ndarray的方式
# 创建元素都为0的ndarray
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
# 创建空ndarray，里面的元素值是内存中的垃圾值，谨慎使用
# 只有打算填充里面的数据时才使用
np.empty((2, 3, 2)) # 创建一个三维的空ndarray

array([[[6.23042070e-307, 4.67296746e-307],
        [1.69121096e-306, 1.29061074e-306],
        [1.69119873e-306, 1.78019082e-306]],

       [[1.89146896e-307, 7.56571288e-307],
        [3.11525958e-307, 1.24610723e-306],
        [1.29061142e-306, 9.20373244e+169]]])

In [11]:
# 创建一个数字序列的ndarray，用法类似python内置的range
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [13]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [14]:
# 创建一个元素都是指定值的ndarray
np.full((2, 3), 1)

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
# 还可以根据另一个ndarray生成一个具有相同形状和数据类型的ndarray
np.zeros_like(np.full((2, 3), 1))

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
np.full_like(np.full((2, 3), 1), 1)

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
np.empty_like(np.full((2, 3), 1))

array([[1944443696,        648,          0],
       [         0,          1, 1851748195]])

In [18]:
# 创建单位矩阵
np.eye?

Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of 

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.identity?

Signature: np.identity(n, dtype=None, *, like=None)
Docstring:
Return the identity array.

The identity array is a square array with ones on
the main diagonal.

Parameters
----------
n : int
    Number of rows (and columns) in `n` x `n` output.
dtype : data-type, optional
    Data-type of the output.  Defaults to ``float``.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    `n` x `n` array with its main diagonal set to one,
    and all other elements 0.

Examples
--------
>>> np.identity(3)
array([[1.,  0.,  0.],
       [0.,  1.,  0.],
       [0.,  0.,  1.]])
File:      d:\python\python3.10\lib\site-packages\numpy\core\numeric.